apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rhopp-250514a-gitops
  description: This is GitOps manifest for rhopp-250514a   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=rhopp-250514a
    backstage.io/kubernetes-id: rhopp-250514a 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: rhopp-250514a
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rhopp-250514a
