apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: rhopp-250514a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  rhopp-250514a
    app.kubernetes.io/part-of: rhopp-250514a-gitops  
  name: rhopp-250514a
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  rhopp-250514a 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  rhopp-250514a
    spec:
      containers:
      - image: registry.redhat.io/ubi9/httpd-24:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081 
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081 
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081 
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi    
        env:
        - name: GIT_REPO
          value: https://github.com/rhopp-rhtap-testing/rhopp-250514a-gitops
      imagePullSecrets:
        - name: tssc-image-registry-auth
